### ISSUE TITLE
PurchaseCompleted event is never fired

### ISSUE THREAD

**Issue by akadko** [adaptyteam/AdaptyUI-React-Native#1]
Hi Adapty team,

I wanted to integrate the paywall builder (thanks for this wonderful feature!) but encountered an issue with it. On iOS, the `onPurchaseCompleted` and `onRestoreCompleted` events are never fired. As a result app can't provide the user with the paid features after the purchase.

I found two things related to it in this RN module and in the AdaptyUI Swift code:

1. A mismatch in the method name:
`RNAUICallHandler.swift`:

```swift
public func paywallController(_ controller: AdaptyPaywallController,
                                  didFinishPurchase product: AdaptyPaywallProduct,
                                  profile: AdaptyProfile) {
...

```
when in fact the third argument should be different:

```swift
public func paywallController(_ controller: AdaptyPaywallController,
                                  didFinishPurchase product: AdaptyPaywallProduct,
                                  purchasedInfo: AdaptyPurchasedInfo) {
...

```
3. And another thing is in the AdaptyUI code. The problem is that the `delegate` instance is `nil` at the moment of handling the purchase result:
`AdaptyPaywallController.swift`:

```swift
private func handlePurchaseResult(_ result: AdaptyResult<AdaptyPurchasedInfo>,
                                      _ product: AdaptyPaywallProduct) {
        switch result {
        case let .success(info):
            delegate?.paywallController(self,
                                        didFinishPurchase: product,
                                        purchasedInfo: info)
        case let .failure(error):
            if error.adaptyErrorCode == .paymentCancelled {
                delegate?.paywallController(self, didCancelPurchase: product)
            } else {
                delegate?.paywallController(self, didFailPurchase: product, error: error)
            }
        }
    }
```

I was able to work around it by simply removing `weak` attribute from the `delegate` field declaration. I'm not a Swift expert so I'm not aware of any consequences of this solution.

Could you guys look into it and provide a solid solution? Thank you!

**Comment by vladd-g** [comment]
hi @akadko, thank you! Could you please check the latest release, 2.0.1?

**Comment by hasanfd** [comment]
Hello,
I have the same issue and I cannot upgrade to 2.0.1 because if the other issue here https://github.com/adaptyteam/AdaptyUI-React-Native/issues/2

"""
In Podfile:
    react-native-adapty-sdk (from `../node_modules/react-native-adapty`) was resolved to 2.9.1, which depends on
      Adapty (= 2.9.2)

    react-native-adapty-ui (from `../node_modules/@adapty/react-native-ui`) was resolved to 2.0.1, which depends on
      Adapty (>= 2.7.0)
"""
And when I forced to use Adapty 2.9.2, I see that AdaptyUI is bind to 2.7.0 and not supporting 2.9.2

Appreciate any help.

**Comment by vladd-g** [comment]
Hello @hasanfd 

Neither v2.0.0 nor v2.0.1 can work with v2.9.x, could you please downgrade it to v2.7.x?

**Comment by hasanfd** [comment]
Thanks @vladd-g, the problem of 2.7.x is purchase completed never works. I am about the launch my product with adapty. However, I am not sure if I can trust just `onLatestProfileLoad` listener in prod. 

```
adapty.addEventListener("onLatestProfileLoad", (profile) => {
```

This is the only way I can get if customer bought anything at the moment.
Any insight about this? Can I go prod with just this listener?

**Comment by vladd-g** [comment]
> the problem of 2.7.x is purchase completed never works

@hasanfd sorry, maybe I didn't get you right; it wasn't the problem of 2.7.x, but of 2.0.0, fixed in 2.0.1. Did you check 2.0.1 with 2.7.x? If you still see the problem, could you please provide more details on it?

**Comment by hasanfd** [comment]
Thanks @vladd-g, looks like events are working on 2.0.1. However, I see an error after every time paywall closes, 

````
 LOG  onCloseButtonPressed
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at removeAllEventListeners (http://10.0.0.77:8081/index.bundle//&platform=ios&dev=true&hot=false:152289:32)
    at unsubscribe (http://10.0.0.77:8081/index.bundle//&platform=ios&dev=true&hot=false:151292:48)
    at ?anon_0_ (http://10.0.0.77:8081/index.bundle//&platform=ios&dev=true&hot=false:151254:41)
    at next (native)
    at fulfilled (http://10.0.0.77:8081/index.bundle//&platform=ios&dev=true&hot=false:150827:32)
    at tryCallOne (/Users/distiller/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/Users/distiller/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://10.0.0.77:8081/index.bundle//&platform=ios&dev=true&hot=false:29717:26)
    at _callTimer (http://10.0.0.77:8081/index.bundle//&platform=ios&dev=true&hot=false:29636:17)
    at _callReactNativeMicrotasksPass (http://10.0.0.77:8081/index.bundle//&platform=ios&dev=true&hot=false:29666:17)
    at callReactNativeMicrotasks (http://10.0.0.77:8081/index.bundle//&platform=ios&dev=true&hot=false:29829:44)
    at __callReactNativeMicrotasks (http://10.0.0.77:8081/index.bundle//&platform=ios&dev=true&hot=false:2751:46)
    at anonymous (http://10.0.0.77:8081/index.bundle//&platform=ios&dev=true&hot=false:2563:45)
    at __guard (http://10.0.0.77:8081/index.bundle//&platform=ios&dev=true&hot=false:2735:15)
    at flushedQueue (http://10.0.0.77:8081/index.bundle//&platform=ios&dev=true&hot=false:2562:21)
    at invokeCallbackAndReturnFlushedQueue (http://10.0.0.77:8081/index.bundle//&platform=ios&dev=true&hot=false:2556:33)
````

Same warning coming after successfull payments as well. Do you think it is important?
Thanks for your quick responses

**Comment by ansh** [comment]
I am getting the same error as @hasanfd 

@vladd-g When can we expect this fixed?

**Comment by vladd-g** [comment]
@hasanfd @ansh could you please check it on the `2.9.3` and `2.1.0`?
